"""Add lieu_rangement to ingredients and statut to liste_courses

Revision ID: 0f684410918a
Revises: 23325a9bb7ee
Create Date: 2025-11-02 08:40:28.208003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f684410918a'
down_revision = '23325a9bb7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lieu_rangement', sa.String(length=100), nullable=True))

    with op.batch_alter_table('liste_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_courses', schema=None) as batch_op:
        batch_op.drop_column('statut')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('lieu_rangement')

    # ### end Alembic commands ###
