"""add type_repas to recette

Revision ID: 12732c0414b7
Revises: c17dec3a3e83
Create Date: 2025-11-03 09:28:47.571283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12732c0414b7'
down_revision = 'c17dec3a3e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_repas', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_column('type_repas')

    # ### end Alembic commands ###
