"""Add quantite_en_stock to ListeCourseItem

Revision ID: 132f8def69e9
Revises: cb75f931ceee
Create Date: 2025-11-02 17:58:48.427687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132f8def69e9'
down_revision = 'cb75f931ceee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_course_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite_en_stock', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_course_items', schema=None) as batch_op:
        batch_op.drop_column('quantite_en_stock')

    # ### end Alembic commands ###
