"""Add onboarding_completed field to User

Revision ID: 195643e0597c
Revises: 26074e731362
Create Date: 2025-11-06 14:08:36.486198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195643e0597c'
down_revision = '26074e731362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
