"""add_contextual_onboarding_to_user

Revision ID: 1d8a40dd5cde
Revises: 81202a830dde
Create Date: 2025-11-09 10:34:29.530181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8a40dd5cde'
down_revision = '81202a830dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_recettes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_menus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_courses', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_courses')
        batch_op.drop_column('onboarding_menus')
        batch_op.drop_column('onboarding_recettes')

    # ### end Alembic commands ###
