"""Add duree_conservation and created_at to ingredients

Revision ID: 23325a9bb7ee
Revises: 9e6a16adef93
Create Date: 2025-11-01 23:21:43.323649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23325a9bb7ee'
down_revision = '9e6a16adef93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duree_conservation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('duree_conservation')

    # ### end Alembic commands ###
