"""Add recettes_favorites association table for saved recipes

Revision ID: 26074e731362
Revises: e736081c4f8f
Create Date: 2025-11-06 14:03:54.852475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26074e731362'
down_revision = 'e736081c4f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recettes_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recette_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recettes_favorites')
    # ### end Alembic commands ###
