"""Add is_public field to Recette for community sharing

Revision ID: 6cf17a549bb3
Revises: d84e908fc0c4
Create Date: 2025-11-06 13:35:24.327624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf17a549bb3'
down_revision = 'd84e908fc0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
