"""add_recette_commentaires_table

Revision ID: 81202a830dde
Revises: e2fd383e2229
Create Date: 2025-11-09 10:10:34.829981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81202a830dde'
down_revision = 'e2fd383e2229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recette_commentaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=False),
    sa.Column('reponse_auteur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recette_commentaires')
    # ### end Alembic commands ###
