"""add units management tables

Revision ID: 9da57683960b
Revises: c47e5f6c8912
Create Date: 2025-11-09 14:52:42.889739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da57683960b'
down_revision = 'c47e5f6c8912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('symbole', sa.String(length=20), nullable=False),
    sa.Column('type_unite', sa.String(length=20), nullable=False),
    sa.Column('unite_base_id', sa.Integer(), nullable=True),
    sa.Column('facteur_vers_base', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unite_base_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('ingredient_conversion_unites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unite_source_id', sa.Integer(), nullable=False),
    sa.Column('unite_cible_id', sa.Integer(), nullable=False),
    sa.Column('facteur_conversion', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unite_cible_id'], ['unites.id'], ),
    sa.ForeignKeyConstraint(['unite_source_id'], ['unites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'unite_source_id', 'unite_cible_id', name='uq_ingredient_conversion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_conversion_unites')
    op.drop_table('unites')
    # ### end Alembic commands ###
