"""Add quantite_achetee to liste_course_items

Revision ID: a3bce3e88d65
Revises: 0f684410918a
Create Date: 2025-11-02 13:45:50.756146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bce3e88d65'
down_revision = '0f684410918a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_course_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite_achetee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liste_course_items', schema=None) as batch_op:
        batch_op.drop_column('quantite_achetee')

    # ### end Alembic commands ###
