"""add_poids_estime_g_to_ingredient

Revision ID: ac76a2ad4ac7
Revises: 12732c0414b7
Create Date: 2025-11-05 00:06:41.597536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac76a2ad4ac7'
down_revision = '12732c0414b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poids_estime_g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('poids_estime_g')

    # ### end Alembic commands ###
