"""Initial schema with updated liste_courses structure

Revision ID: b8fb0ffea4d1
Revises: 
Create Date: 2025-11-01 22:22:32.897018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fb0ffea4d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('unite_mesure', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_categorie'), ['categorie'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_nom'), ['nom'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('nb_personnes', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menus_date_debut'), ['date_debut'], unique=False)

    op.create_table('recettes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=True),
    sa.Column('temps_preparation', sa.String(length=50), nullable=True),
    sa.Column('temps_cuisson', sa.String(length=50), nullable=True),
    sa.Column('evaluation', sa.Integer(), nullable=True),
    sa.Column('auteur_nom', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recettes_nom'), ['nom'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liste_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_jours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('jour_semaine', sa.Integer(), nullable=False),
    sa.Column('petit_dejeuner_recette_id', sa.Integer(), nullable=True),
    sa.Column('dejeuner_recette_id', sa.Integer(), nullable=True),
    sa.Column('diner_recette_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dejeuner_recette_id'], ['recettes.id'], ),
    sa.ForeignKeyConstraint(['diner_recette_id'], ['recettes.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['petit_dejeuner_recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recette_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recette_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recette_id'], ['recettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liste_course_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liste_id', sa.Integer(), nullable=False),
    sa.Column('nom_ingredient', sa.String(length=100), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('rayon', sa.String(length=50), nullable=True),
    sa.Column('achete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['liste_id'], ['liste_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liste_course_items')
    op.drop_table('recette_ingredients')
    op.drop_table('menu_jours')
    op.drop_table('liste_courses')
    op.drop_table('instructions')
    op.drop_table('stock')
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recettes_nom'))

    op.drop_table('recettes')
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menus_date_debut'))

    op.drop_table('menus')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_nom'))
        batch_op.drop_index(batch_op.f('ix_ingredients_categorie'))

    op.drop_table('ingredients')
    # ### end Alembic commands ###
