"""add mois_saison to recette

Revision ID: c17dec3a3e83
Revises: 132f8def69e9
Create Date: 2025-11-02 19:12:18.376809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17dec3a3e83'
down_revision = '132f8def69e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mois_saison', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_column('mois_saison')

    # ### end Alembic commands ###
