"""add_portions_min_and_est_divisible_to_recette

Revision ID: c47e5f6c8912
Revises: 1d8a40dd5cde
Create Date: 2025-11-09 10:38:43.849259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47e5f6c8912'
down_revision = '1d8a40dd5cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portions_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('est_divisible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_column('est_divisible')
        batch_op.drop_column('portions_min')

    # ### end Alembic commands ###
