"""Add mois_saison and stock_limite to Ingredient

Revision ID: cb75f931ceee
Revises: a3bce3e88d65
Create Date: 2025-11-02 14:27:01.712960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb75f931ceee'
down_revision = 'a3bce3e88d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mois_saison', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('stock_limite', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('stock_limite')
        batch_op.drop_column('mois_saison')

    # ### end Alembic commands ###
