"""Remove photo_url from recettes

Revision ID: d4f5a6b7c8d9
Revises: cb75f931ceee
Create Date: 2025-11-06 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f5a6b7c8d9'
down_revision = 'cb75f931ceee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recettes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###
