"""Add gouter to menu_jours

Revision ID: e5f6g7h8i9j0
Revises: c6ae504eba40
Create Date: 2025-11-06 09:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6g7h8i9j0'
down_revision = 'c6ae504eba40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_jours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gouter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_menu_jours_gouter_recettes', 'recettes', ['gouter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_jours', schema=None) as batch_op:
        batch_op.drop_constraint('fk_menu_jours_gouter_recettes', type_='foreignkey')
        batch_op.drop_column('gouter_id')

    # ### end Alembic commands ###
